version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - net_front

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - net_back
      - net_front

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - net_back
      - net_front

volumes:
  post_db:

networks:
  net_back:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24

  net_front:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
